name: CI for Spark Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Apache Spark
        run: |
          wget -qO- "https://archive.apache.org/dist/spark/spark-3.1.1/spark-3.1.1-bin-hadoop2.7.tgz" | tar -xz -C /tmp/
          echo "SPARK_HOME=/tmp/spark-3.1.1-bin-hadoop2.7" >> $GITHUB_ENV
          echo "$SPARK_HOME/bin" >> $GITHUB_PATH

      - name: Debug Python Environment
        run: |
          echo "Python Version:"
          python --version
          echo "Python Path:"
          python -c "import sys; print(sys.path)"
          echo "Contents of src directory:"
          ls -l ${{ github.workspace }}/src

      - name: Run main.py using spark-submit
        env:
          SPARK_HOME: /tmp/spark-3.1.1-bin-hadoop2.7
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          $SPARK_HOME/bin/spark-submit --master local[2] --name "MovieLens Data Processing" src/main.py

      - name: Run PySpark tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src:${{ github.workspace }}/tests
        run: |
          pytest tests/
